### ISSUE TITLE
Getting this plugin to work ?

### ISSUE THREAD

**Issue by bepolymathe** [sgros/Everdo-Thunderbird-Plugin#1]
Hello @sgros, 

I would like to use this plugin (thanks for the initiative) but I can't get it to work. I have defined the following security exception... 

![image](https://user-images.githubusercontent.com/29939805/143206209-f2557285-f0dd-48b6-9b8b-9dd8a78cfe9e.png)

And configure the plugin in the same way. 
![image](https://user-images.githubusercontent.com/29939805/143206312-f8c26b10-8a15-4b37-870a-fc386aace7f0.png)

Did I miss something ?
Have a nice day.

**Comment by bepolymathe** [comment]
Can i ping you @terastream @sgros ?

**Comment by sgros** [comment]
I'm not using Everdo any more so I don't know what might be a problem. If I find time, I'll try to look at it during the weekend.

**Comment by bepolymathe** [comment]
Ok. I finally find a solution. Thanks. 
Out of curiosity... what are you using instead ?

**Comment by sgros** [comment]
I was using Planner (https://github.com/alainm23/planner/) but currently I'm using just mail client.
